/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Modulo;
import javax.swing.JOptionPane;

/**
 *
 * @author Clark
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        ocultarMenu(0);
    }

    public MenuPrincipal(int nivel) {
        initComponents();
        this.setLocationRelativeTo(null);
        ocultarMenu(nivel);

    }

    private void ocultarMenu(int nivel) {
        if (nivel == 0) {//login
            this.mnuCerrarSesion.setVisible(false);
            this.mnuAlumnos.setVisible(false);
            this.mnuAsignaturas.setVisible(false);
            this.mnuDocentes.setVisible(false);
            this.mnuNotas.setVisible(false);
            this.mnuCursos.setVisible(false);
            this.mnuUsuarios.setVisible(false);
        }
        if (nivel == 64) {//admin
            this.mnuCerrarSesion.setVisible(true);
            this.mnuAlumnos.setVisible(true);
            this.mnuAsignaturas.setVisible(true);
            this.mnuDocentes.setVisible(true);
            this.mnuNotas.setVisible(true);
            this.mnuCursos.setVisible(true);
            this.mnuUsuarios.setVisible(true);
        }
        if (nivel == 32) {//profe
            this.mnuCerrarSesion.setVisible(true);
            this.mnuAlumnos.setVisible(false);
            this.mnuAsignaturas.setVisible(false);
            this.mnuDocentes.setVisible(false);
            this.mnuNotas.setVisible(true);
            this.mnuCursos.setVisible(false);
            this.mnuUsuarios.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuConexion = new javax.swing.JMenu();
        mnuIniciarSesion = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        mnuAlumnos = new javax.swing.JMenu();
        mnuAsignaturas = new javax.swing.JMenu();
        mnuCursos = new javax.swing.JMenu();
        mnuDocentes = new javax.swing.JMenu();
        mnuDocentesAdm = new javax.swing.JMenuItem();
        mnuNotas = new javax.swing.JMenu();
        mnuUsuarios = new javax.swing.JMenu();
        mnuAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("School Now ! V1.0");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("Archivo");

        mnuConexion.setText("Conexion");

        mnuIniciarSesion.setText("Iniciar Sesion");
        mnuIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIniciarSesionActionPerformed(evt);
            }
        });
        mnuConexion.add(mnuIniciarSesion);

        mnuCerrarSesion.setText("Cerrar Sesion");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuConexion.add(mnuCerrarSesion);

        jMenu1.add(mnuConexion);
        jMenu1.add(jSeparator1);

        mnuSalir.setText("Salir");
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        mnuAlumnos.setText("Alumnos");
        jMenuBar1.add(mnuAlumnos);

        mnuAsignaturas.setText("Asignaturas");
        jMenuBar1.add(mnuAsignaturas);

        mnuCursos.setText("Cursos");
        jMenuBar1.add(mnuCursos);

        mnuDocentes.setText("Docentes");

        mnuDocentesAdm.setText("Administrar");
        mnuDocentesAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDocentesAdmActionPerformed(evt);
            }
        });
        mnuDocentes.add(mnuDocentesAdm);

        jMenuBar1.add(mnuDocentes);

        mnuNotas.setText("Notas");
        jMenuBar1.add(mnuNotas);

        mnuUsuarios.setText("Usuarios");
        jMenuBar1.add(mnuUsuarios);

        mnuAcercaDe.setText("Acerca de...");
        jMenuBar1.add(mnuAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIniciarSesionActionPerformed
        Login l = new Login(this, true);
        l.setLocationRelativeTo(null);
        l.setVisible(true);;
        this.dispose();


    }//GEN-LAST:event_mnuIniciarSesionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
          MenuPrincipal m = new MenuPrincipal(0);
            m.setLocationRelativeTo(null);
            m.setVisible(true);
            this.dispose();

    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    private void mnuDocentesAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDocentesAdmActionPerformed
    Modulo.admDocentes = new AdmDocentes(this,true);
      
      Modulo.admDocentes.setLocationRelativeTo(null);
      Modulo.admDocentes.setVisible(true);
    }//GEN-LAST:event_mnuDocentesAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;








                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnuAcercaDe;
    private javax.swing.JMenu mnuAlumnos;
    private javax.swing.JMenu mnuAsignaturas;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenu mnuConexion;
    private javax.swing.JMenu mnuCursos;
    private javax.swing.JMenu mnuDocentes;
    private javax.swing.JMenuItem mnuDocentesAdm;
    private javax.swing.JMenuItem mnuIniciarSesion;
    private javax.swing.JMenu mnuNotas;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
